// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqpyOv-_s6JeGXJmUMQPrFCKGQohOS3VI',
    appId: '1:678307364627:web:94f6029a3adbfaee23a4e6',
    messagingSenderId: '678307364627',
    projectId: 'chaching-8ea96',
    authDomain: 'chaching-8ea96.firebaseapp.com',
    databaseURL: 'https://chaching-8ea96-default-rtdb.firebaseio.com',
    storageBucket: 'chaching-8ea96.appspot.com',
    measurementId: 'G-9F0382S1CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiIdCaL3hZ2FUtOMlUcOY5H_qIDUZ2KoQ',
    appId: '1:678307364627:android:6d69b84059037c0b23a4e6',
    messagingSenderId: '678307364627',
    projectId: 'chaching-8ea96',
    databaseURL: 'https://chaching-8ea96-default-rtdb.firebaseio.com',
    storageBucket: 'chaching-8ea96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM2lsIRGVueT4uqeZpT5tlVueCp2sojH4',
    appId: '1:678307364627:ios:e0eedc078df3d2b823a4e6',
    messagingSenderId: '678307364627',
    projectId: 'chaching-8ea96',
    databaseURL: 'https://chaching-8ea96-default-rtdb.firebaseio.com',
    storageBucket: 'chaching-8ea96.appspot.com',
    androidClientId: '678307364627-7mh99bru4cjr47l98oof9huve5t6up73.apps.googleusercontent.com',
    iosClientId: '678307364627-e6huc1jers9but22mhmi93ssh9higjk4.apps.googleusercontent.com',
    iosBundleId: 'com.hungps.flutterpokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM2lsIRGVueT4uqeZpT5tlVueCp2sojH4',
    appId: '1:678307364627:ios:8309f8f29ae238f523a4e6',
    messagingSenderId: '678307364627',
    projectId: 'chaching-8ea96',
    databaseURL: 'https://chaching-8ea96-default-rtdb.firebaseio.com',
    storageBucket: 'chaching-8ea96.appspot.com',
    androidClientId: '678307364627-7mh99bru4cjr47l98oof9huve5t6up73.apps.googleusercontent.com',
    iosClientId: '678307364627-47jhstimrq8k0t4fpvt5dttcev12i0h0.apps.googleusercontent.com',
    iosBundleId: 'com.hungps.flutterPokedex',
  );
}
